### POST request to create new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Nisa Rizkiana",
  "email": "nisarizkiana070@gmail.com",
  "address": "Green Harmoni, Bandung",
  "dateOfBirth": "1997-03-20",
  "registeredDate": "2025-07-11"
}
###