### POST request to create new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Bayezid Rasyid Ibrahim",
  "email": "bayezid@gmail.com",
  "address": "Green Harmoni, Bandung",
  "dateOfBirth": "2025-03-01",
  "registeredDate": "2025-07-11"
}
###