### PUT request to update patient
PUT http://localhost:4000/patients/20746812-0216-4ed2-9b84-db510641b27e
Content-Type: application/json

{
  "name": "Bayezid Rasyid",
  "email": "bayezid@gmail.com",
  "address": "Bandung",
  "dateOfBirth": "1992-07-25"
}
###